"""Jinja2 HTML email template rendering."""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, select_autoescape

from lexflow_api.domain.notification_events import EMAIL_TEMPLATE_MAP, NotificationEventType

TEMPLATES_DIR = Path(__file__).resolve().parents[4] / "templates" / "emails"


@lru_cache(maxsize=1)
def _env() -> Environment:
    return Environment(
        loader=FileSystemLoader(str(TEMPLATES_DIR)),
        autoescape=select_autoescape(["html", "xml"]),
    )


def render_email(
    event_type: NotificationEventType,
    context: dict[str, Any],
) -> tuple[str, str]:
    """Return (subject, html_body)."""
    template_name = EMAIL_TEMPLATE_MAP.get(event_type, "workflow-completed")
    env = _env()
    ctx = {**context, "event_type": event_type.value}
    html = env.get_template(f"{template_name}.html").render(**ctx)
    subject = str(context.get("subject") or context.get("email_subject") or _default_subject(event_type, context))
    return subject, html


def render_plain_summary(context: dict[str, Any]) -> str:
    lines = [
        str(context.get("headline", "LexFlow AI Workflow Notification")),
        f"Status: {context.get('status_badge', 'Update')}",
    ]
    if context.get("case_title"):
        lines.append(f"Case: {context['case_title']}")
    if context.get("client_name"):
        lines.append(f"Client: {context['client_name']}")
    if context.get("workflow_name"):
        lines.append(f"Workflow: {context['workflow_name']}")
    if context.get("current_stage"):
        lines.append(f"Stage: {context['current_stage']}")
    lines.append(str(context.get("footer_note", "Generated by LexFlow AI Workflow Engine.")))
    return "\n".join(lines)


def _default_subject(event_type: NotificationEventType, context: dict[str, Any]) -> str:
    case = context.get("case_title") or "Case Update"
    status = context.get("status_badge") or "Notification"
    return f"[LexFlow] {status} — {case}"
